-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.end_event(event_id integer, team1_members text[], team2_members text[], team1_win boolean, team1_scores integer[], team2_scores integer[])
--  RETURNS SETOF events
--  LANGUAGE plpgsql
-- AS $function$
-- DECLARE
--     p_event_id alias for $1;
--     team1_id INT;
--     team2_id INT;
-- BEGIN
--     INSERT INTO event_teams (event_id, set_scores) VALUES (p_event_id, array_to_json(team1_scores::int[])) RETURNING team_id INTO team1_id;
--     INSERT INTO event_teams (event_id, set_scores) VALUES (event_id, array_to_json(team2_scores::int[])) RETURNING team_id INTO team2_id;
--     IF team1_win = TRUE THEN
--         UPDATE events SET status = 'closed', winner_id = team1_id, end_date = now() WHERE events.event_id = p_event_id;
--     ELSE
--         UPDATE events SET status = 'closed', winner_id = team2_id, end_date = now() WHERE events.event_id = p_event_id;
--     END IF;
--     DELETE FROM event_attendees AS a WHERE a.event_id = p_event_id AND a.status = 'invited';
-- END;
-- $function$;
