-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO notification_status (value, description) VALUES ('read', 'notification was read by user'), ('unread', 'notification was not read by user');
